### ISSUE TITLE
App Crashes if backgrounded while performing login

### ISSUE THREAD

**Issue by alan-rodriguez** [mikedunbar/AndroidCleanArchitectureLoginExample#1]
`LoginPresenter.detachView()` only sets the view reference in the presenter to be null, it doesn't cancel the subscription in `LoginUseCase` or prevent methods from being called on the view when it is null.

This means when you send the LoginActivity to the background within 2 seconds (the sleep duration to simulate a Network call) after clicking the Sign In button, it will result in a NullPointerException and crash the app.

**Comment by mikedunbar** [comment]
Doh - good catch! I will take a look and aim to fix that today or tomorrow.

**Comment by mikedunbar** [comment]
It was some haphazard logging code causing the crash - LoginPresenter.logThreadState. I forgot to have it check for a non-null loginView, which it was using for logging. I replaced this with a more straight-forward approach of passing a Logger object (backed by an Android-specific imply) to LoginPresenter.

All the "real" methods in LoginPresenter were checking for a non-null loginView before trying to update it. I took the approach of not canceling the subscription in LoginUseCase, so that when the app is background and later returned to the foreground it could leverage the already-executed login request. But in the case of a phone rotation, a new activity gets a new presenter and the original requested is unused anyhow. A future improvement there would be to use an activity-scoped presenter in the Dagger code, so even a new activity instance would hopefully use the same LoginPresenter and not have to redo the login request. Or using the ViewModel from Android Architecture Components would likely achieve the same effect.

I also noticed that I had forgotten to push some changes from last month, were I moved the authentication logic into a UserRepository class and out of the use case class.
